defaults: &defaults
  adapter:  mysql2
  pool:     5
  encoding: utf8
  database: api_scrum_rb_<%= Rails.env %>
  username: api_scrum
  password: api_scrum
  host:     db.api.scrum.rb.lxc

development:
  <<: *defaults

test:
  <<: *defaults
