require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SprintBacklogsController do

  # This should return the minimal set of attributes required to create a valid
  # SprintBacklog. As you add validations to SprintBacklog, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SprintBacklogsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all sprint_backlogs as @sprint_backlogs" do
      sprint_backlog = SprintBacklog.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sprint_backlogs).should eq([sprint_backlog])
    end
  end

  describe "GET show" do
    it "assigns the requested sprint_backlog as @sprint_backlog" do
      sprint_backlog = SprintBacklog.create! valid_attributes
      get :show, {:id => sprint_backlog.to_param}, valid_session
      assigns(:sprint_backlog).should eq(sprint_backlog)
    end
  end

  describe "GET new" do
    it "assigns a new sprint_backlog as @sprint_backlog" do
      get :new, {}, valid_session
      assigns(:sprint_backlog).should be_a_new(SprintBacklog)
    end
  end

  describe "GET edit" do
    it "assigns the requested sprint_backlog as @sprint_backlog" do
      sprint_backlog = SprintBacklog.create! valid_attributes
      get :edit, {:id => sprint_backlog.to_param}, valid_session
      assigns(:sprint_backlog).should eq(sprint_backlog)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SprintBacklog" do
        expect {
          post :create, {:sprint_backlog => valid_attributes}, valid_session
        }.to change(SprintBacklog, :count).by(1)
      end

      it "assigns a newly created sprint_backlog as @sprint_backlog" do
        post :create, {:sprint_backlog => valid_attributes}, valid_session
        assigns(:sprint_backlog).should be_a(SprintBacklog)
        assigns(:sprint_backlog).should be_persisted
      end

      it "redirects to the created sprint_backlog" do
        post :create, {:sprint_backlog => valid_attributes}, valid_session
        response.should redirect_to(SprintBacklog.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sprint_backlog as @sprint_backlog" do
        # Trigger the behavior that occurs when invalid params are submitted
        SprintBacklog.any_instance.stub(:save).and_return(false)
        post :create, {:sprint_backlog => {  }}, valid_session
        assigns(:sprint_backlog).should be_a_new(SprintBacklog)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SprintBacklog.any_instance.stub(:save).and_return(false)
        post :create, {:sprint_backlog => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sprint_backlog" do
        sprint_backlog = SprintBacklog.create! valid_attributes
        # Assuming there are no other sprint_backlogs in the database, this
        # specifies that the SprintBacklog created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SprintBacklog.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => sprint_backlog.to_param, :sprint_backlog => { "these" => "params" }}, valid_session
      end

      it "assigns the requested sprint_backlog as @sprint_backlog" do
        sprint_backlog = SprintBacklog.create! valid_attributes
        put :update, {:id => sprint_backlog.to_param, :sprint_backlog => valid_attributes}, valid_session
        assigns(:sprint_backlog).should eq(sprint_backlog)
      end

      it "redirects to the sprint_backlog" do
        sprint_backlog = SprintBacklog.create! valid_attributes
        put :update, {:id => sprint_backlog.to_param, :sprint_backlog => valid_attributes}, valid_session
        response.should redirect_to(sprint_backlog)
      end
    end

    describe "with invalid params" do
      it "assigns the sprint_backlog as @sprint_backlog" do
        sprint_backlog = SprintBacklog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SprintBacklog.any_instance.stub(:save).and_return(false)
        put :update, {:id => sprint_backlog.to_param, :sprint_backlog => {  }}, valid_session
        assigns(:sprint_backlog).should eq(sprint_backlog)
      end

      it "re-renders the 'edit' template" do
        sprint_backlog = SprintBacklog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SprintBacklog.any_instance.stub(:save).and_return(false)
        put :update, {:id => sprint_backlog.to_param, :sprint_backlog => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sprint_backlog" do
      sprint_backlog = SprintBacklog.create! valid_attributes
      expect {
        delete :destroy, {:id => sprint_backlog.to_param}, valid_session
      }.to change(SprintBacklog, :count).by(-1)
    end

    it "redirects to the sprint_backlogs list" do
      sprint_backlog = SprintBacklog.create! valid_attributes
      delete :destroy, {:id => sprint_backlog.to_param}, valid_session
      response.should redirect_to(sprint_backlogs_url)
    end
  end

end
